WIP: Restructure to support ansible collections and fix sanity test issues.
zhmcclient/zhmc-ansible-modules pull request #139
Opened 2020-08-14 20:56 UTC by sabyadi

See commit message.

2020-08-14 20:56 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 2668f6496cdd8f4c2d62d7129e59684d5954fc32
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2020-09-11 14:09 UTC, andy-maier commented on README.md
> +zhmc-ansible-modules - Ansible modules for the IBM Z HMC Web Services API
Seems this one is resolved.

2020-09-11 14:26 UTC, andy-maier requested changes
See comment.

2020-09-11 14:26 UTC, andy-maier commented on docs/intro.rst
> +      (myenv)# pip install zhmc-ansible-modules
One does not need to be root to do this.
Usually, the `#` prompt indicates root, and the `$` prompt indicates non-root users.

2020-09-11 14:54 UTC, andy-maier commented
I have resolved the merge conflict, and have resolved my own comment about the `#` vs. `$` prompt, in order to get this PR merged. We can still change the prompt again if there is disagreement.

2020-09-11 14:54 UTC, andy-maier commented on docs/intro.rst
> +      (myenv)# pip install zhmc-ansible-modules
DONE

2020-09-21 14:14 UTC, andy-maier commented
I backed out my change for '#' prompt back to '$', to allow it to succeed the checks.

2020-09-21 17:06 UTC, merged