[WIP] 1.1: Added zhmc_cpc_capacity module
zhmcclient/zhmc-ansible-modules pull request #234
Opened 2020-11-13 10:15 UTC by andy-maier

WIP TODOs:
* Rebase once 1.1 has been started
* Add function tests
* zhmcclient: Add support for add/remove temporary capacity operations & mock support

2021-04-13 00:09 UTC, vkathir82 requested changes
Need update in the documentation side as specified

2021-04-13 00:09 UTC, vkathir82 commented on docs/source/modules/zhmc_cpc_capacity.rst
> +specialty_processors
I believe this parameter represent "processor-info" object values in the  "Add Temporary Capacity" API call which contains 'processor-type' as represented below. But this also contains an optional 'num-processor-steps' which represents The delta to the current number of processors. Do we need to support this optional parameter as well ?

2021-04-13 00:09 UTC, vkathir82 commented on docs/source/modules/zhmc_cpc_capacity.rst
> +     register: cap1
I understand "register" is our ansible module specific variable to name the capacity group which I don't see with WS API call. Do we need to mention this in the above "Parameters" list ?

2021-04-29 11:27 UTC, andy-maier commented on docs/source/modules/zhmc_cpc_capacity.rst
> +  | **required**: False
NO CHANGE.

At the level of the WS API, the test parameter is always provided. See `zhmcclient.Cpc.add_temporary_capacity()`. That method already provides a default of False for it at its method interface. The ansible module also treats it as optional with a default of False.

So there is no error here, but the question is instead should we or should we not default parameters at the zhmcclient or ansible module level, that are required at the HMC API level. I believe that this is something we can rightfully do if we think it makes sense. In this case, I think it does make sense, particularly because the test mode seems to be quite rare.

2021-04-29 11:39 UTC, andy-maier commented on docs/source/modules/zhmc_cpc_capacity.rst
> +specialty_processors
When reviewing the code, it turns out there is a significant hickup here, since the code processing the input assumes it comes in the form of a "properties" input parameter with an "add_temporary_capacity" property, while the documentation states it comes as a "specialty_processors" input parameter. Needs to be fixed in the code.

Regarding your question: The idea is that the input is easy to understand and is then translated into the rather complex input for the HMC operations. Also, whether Add Capacity or Remove Capacity or even Update Properties is used, depends on the specific change. There is no 1:1 maping between ansible module input parameters and HMC operation input parameters.

The 'num-processor-steps'  input parameter of the Add Capacity operation needs to be calculated from the Ansible module input. That would have been part of the code that is missing.

2021-04-29 11:40 UTC, andy-maier commented on docs/source/modules/zhmc_cpc_capacity.rst
> +     register: cap1
NO CHANGE
"register" is a generic Ansible task parameter and tells Ansible to save the module output in that variable. Our module does not see that parameter at all.

2021-04-29 11:41 UTC, andy-maier commented
I marked the comments as resolved that I responded to. If you feel different, please reopen them by marking them as unresolved, then we can discuss.

2023-10-31 06:47 UTC, andy-maier commented
Adjusted the new module to current module standards.

2024-02-12 07:46 UTC, andy-maier commented
Resolved conflicts on sanity ignore files, and adjusted the new module to current module standards.

2024-02-12 15:22 UTC, andy-maier commented on docs/source/modules/zhmc_cpc_capacity.rst
> +specialty_processors
I have reimplemented the module. PLease re-reviw.

2024-02-12 15:23 UTC, andy-maier commented
I have pretty much reimplemented the module since there were too many flaws. Also the input parameters have been extended and partly changed.

2024-02-13 09:36 UTC, andy-maier commented
I just added an end2end testcase for state=facts.

2024-02-20 17:39 UTC, anilak11 approved these changes
Looks good to me

2024-02-20 17:39 UTC, anilak11 commented on plugins/modules/zhmc_cpc_capacity.py
> +    for hmc_name in CPC_CAPACITY_PROPERTIES:
rename hmc_name to something like capacity_property/ property.

2024-06-24 16:12 UTC, andy-maier commented on plugins/modules/zhmc_cpc_capacity.py
> +    for hmc_name in CPC_CAPACITY_PROPERTIES:
DONE - renamed it to "prop_name".

2024-07-03 11:01 UTC, andy-maier commented
I worked through the discussion in the slack channel and made several changes based on that. Also, I accommodated for the fact that some capacity related CPC properties were introduced only on SE 2.16.0.
Requires re-review.

2024-07-08 12:47 UTC, simon-spinner commented on plugins/modules/zhmc_cpc_capacity.py
> +        target_processor_dict(dict): Dict with target numbers of the specialty
```suggestion
        target_processor(dict): Dict with target numbers of the specialty
```

2024-07-08 13:10 UTC, andy-maier commented on plugins/modules/zhmc_cpc_capacity.py
> +    I all parameters and return values, dict key is the processor type and dict
Changed "I" to "In". DONE.

2024-07-08 13:10 UTC, andy-maier commented on plugins/modules/zhmc_cpc_capacity.py
> +        target_processor_dict(dict): Dict with target numbers of the specialty
Changed to `target_processors`. DONE

2024-07-08 13:12 UTC, andy-maier commented on plugins/modules/zhmc_cpc_capacity.py
> +            if proc_key == 'ifl':
Correct. This is the processing of specialty processors, which does not include CPs. CPs are handled only as part of changing the software model.

2024-07-08 13:14 UTC, simon-spinner approved these changes

2024-07-08 14:37 UTC, merged