Improved return value docs and samples
zhmcclient/zhmc-ansible-modules pull request #250
Opened 2020-11-20 17:08 UTC by andy-maier

See commit message.

2020-11-20 17:08 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: e0a0ef9642addd737ace90c5258799b7aaed971a
  * Your commit message body contains a line that is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2020-11-22 20:06 UTC, sabyadi commented on plugins/modules/zhmc_adapter.py
> +          description: "Additional properties of the port, as described for the
"as described in"

2020-11-22 20:07 UTC, sabyadi commented on plugins/modules/zhmc_adapter.py
> +      description: "Additional properties of the adapter, as described for the
"as described in"

2020-11-22 20:12 UTC, sabyadi commented on plugins/modules/zhmc_crypto_attachment.py
> +      - "Only for C(state=attached): The crypto type of the crypto adapters
Since physically the CEX adapters are the same, they do not have a type, but operate in a given "mode".

2020-11-22 20:12 UTC, andy-maier commented on plugins/modules/zhmc_adapter.py
> +          description: "Additional properties of the port, as described for the
Ok, agreed. Will change all occurrences of it.

2020-11-22 20:13 UTC, andy-maier commented on plugins/modules/zhmc_adapter.py
> +      description: "Additional properties of the adapter, as described for the
agreed, see previous response.

2020-11-22 20:15 UTC, sabyadi commented on plugins/modules/zhmc_adapter.py
> +  type: bool
Should be of type str.

2020-11-22 20:17 UTC, andy-maier commented on plugins/modules/zhmc_crypto_attachment.py
> +      - "Only for C(state=attached): The crypto type of the crypto adapters
In the data model of adapters, the WS API book defines the property named "crypto-type" for that, and describes it as "Crypto type".
The current text in the description is consistent with that.

2020-11-22 20:17 UTC, andy-maier commented on plugins/modules/zhmc_adapter.py
> +  type: bool
Agreed. Will change it in all occurrences.

2020-11-22 20:18 UTC, sabyadi commented on plugins/modules/zhmc_crypto_attachment.py
>      default: 'ep11'
Should it be "ep11-coprocessor" like shown in the same output on line 309?

2020-11-22 20:20 UTC, sabyadi commented on plugins/modules/zhmc_partition.py
> +        storage-menegement feature enabled (ie. before z15), the list is
"management"

2020-11-22 20:22 UTC, andy-maier commented on plugins/modules/zhmc_adapter.py
> +          description: "Additional properties of the port, as described for the
DONE

2020-11-22 20:24 UTC, andy-maier commented on plugins/modules/zhmc_adapter.py
> +  type: bool
DONE

2020-11-22 20:24 UTC, sabyadi commented on plugins/modules/zhmc_user.py
> +            for the data model of the 'Password Rule' object in the
Probably 'ldap server' object.

2020-11-22 20:25 UTC, sabyadi requested changes
Please have a look at my comments.

2020-11-22 20:27 UTC, andy-maier commented on plugins/modules/zhmc_crypto_attachment.py
>      default: 'ep11'
No, 'ep11' is correct. this is one if the cases where the input parameters are simplified. the translation is done using the `CRYPTO_TYPES_MOD2HMC` dict. Unfortunately, the backwards translation is not performed for the result data. In hindsight we probably should not have attempted to simplify the input parameter.

2020-11-22 20:28 UTC, andy-maier commented on plugins/modules/zhmc_partition.py
> +        storage-menegement feature enabled (ie. before z15), the list is
DONE

2020-11-22 20:28 UTC, andy-maier commented on plugins/modules/zhmc_user.py
> +            for the data model of the 'Password Rule' object in the
Oops. Good catch. DONE

2020-11-22 20:31 UTC, andy-maier commented
I rebased, resolved the merge conflicts, and resolved those of Adilet's comments that are marked as resolved.

2020-11-22 22:08 UTC, merged