Added upgrade_timeout parameter to zhmc_console and zhmc_cpc modules
zhmcclient/zhmc-ansible-modules pull request #843
Opened 2023-12-19 14:49 UTC by abhirams-1

- Added upgrade_timeout parameter to zhmc_console and zhmc_cpc modules
- Added entry for change in release_notes.rst

Signed-off by Abhiram Santhosh <abhiram.santhosh1@ibm.com>

2023-12-19 14:49 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 7bc5a1ad36e45d3fb53e896c66675a0c96253b27
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2023-12-19 14:50 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 6aaa31000792a74d508a6b9acd0432fc8f2b6b0b
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2023-12-19 15:11 UTC, andy-maier requested changes

2023-12-19 15:11 UTC, andy-maier commented on plugins/modules/zhmc_console.py
> +      - "Timeout in seconds for waiting for completion of upgrade (e.g. 3600)"
Since this is an optional parameter, it should either state its default in the description, or the "default" property should be set to the default. I prefer setting the "default" property, then you have it all defined in this project, and you do not rely on the default of the zhmcclient library.

2023-12-19 15:18 UTC, abhirams-1 commented on plugins/modules/zhmc_console.py
> +      - "Timeout in seconds for waiting for completion of upgrade (e.g. 3600)"
Added default timeout of 3600 seconds.

2023-12-19 15:18 UTC, abhirams-1 commented on plugins/modules/zhmc_cpc.py
> +      - "Timeout in seconds for waiting for completion of upgrade (e.g. 10800)"
Added default timeout of 10800 seconds

2023-12-20 05:16 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 2351eaf70e9f4ea953088669b352c47fe410c91c
  * Invalid signoff. Commit message must end with  
    **Signed-off-by: .* <.*>**

Guidelines are available at https://github.com/zhmcclient/zhmc-ansible-modules/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

2023-12-20 06:27 UTC, andy-maier approved these changes

2023-12-20 06:27 UTC, merged