Obscure password in log messages
zhmcclient/zhmc-ansible-modules pull request #970
Opened 2024-06-03 06:27 UTC by abhirams-1

Changes:
- Obscure 'password' property in log messages.

Fixes https://github.com/zhmcclient/zhmc-ansible-modules/issues/967

2024-06-03 08:57 UTC, andy-maier requested changes

2024-06-03 08:57 UTC, andy-maier commented on plugins/modules/zhmc_user.py
> +                        user_name, update_props)
I would prefer to have only one `LOGGER.debug()` call in the code, so you could rename `_update_props_masked` to `logged_props` and set it in both cases.

2024-06-03 08:57 UTC, andy-maier commented on plugins/modules/zhmc_user.py
> +                    _update_props_masked = deepcopy(update_props)
You don't need a deep copy, since the purpose of the copy is just to remove one dict item:
```
_update_props_masked = dict(update_props)
```

2024-06-03 08:57 UTC, andy-maier commented on plugins/modules/zhmc_user.py
> +                    _update_props_masked['password'] = "<hidden>"    # nosec
In thge zhmcclient project, we use:
```
BLANKED_OUT = '********'  # Replacement for blanked out sensitive values
```
I suggest to define such a constant here as well (e.g. in `plugins/module_utils/common.py`) and use it.

2024-06-03 08:57 UTC, andy-maier commented on plugins/modules/zhmc_user.py
> +    _params = deepcopy(dict(module.params))
`dict()` already creates a shallow copy, so now you have a (deep) copy of a (shallow) copy.

Please remove the `dict()`:
```
_params = deepcopy(module.params)
```

2024-06-03 08:57 UTC, andy-maier commented on plugins/modules/zhmc_user.py
> +        _params['properties']['password'] = "<hidden>"    # nosec
Please also change to use asterisks, e.g. by using the **`BLANKED_OUT` constant - see earlier comment.

2024-06-03 08:57 UTC, andy-maier commented on plugins/modules/zhmc_user.py
>                      user.update_properties(update_props)
You also need to blank out the "password" property in the `result` dict returned by this method. That is best done at the end of the method, just before it is returned.

Also, this is an incompatible change for users, so please add an according entry in the change log (`docs/source/release_notes.rst`).

2024-06-10 04:30 UTC, abhirams-1 commented on plugins/modules/zhmc_user.py
>                      user.update_properties(update_props)
Done

2024-06-10 04:30 UTC, abhirams-1 commented on plugins/modules/zhmc_user.py
> +        _params['properties']['password'] = "<hidden>"    # nosec
Done

2024-06-10 04:30 UTC, abhirams-1 commented on plugins/modules/zhmc_user.py
> +    _params = deepcopy(dict(module.params))
Done

2024-06-10 04:30 UTC, abhirams-1 commented on plugins/modules/zhmc_user.py
> +                    _update_props_masked['password'] = "<hidden>"    # nosec
Done

2024-06-10 04:30 UTC, abhirams-1 commented on plugins/modules/zhmc_user.py
> +                    _update_props_masked = deepcopy(update_props)
Done

2024-06-10 04:30 UTC, abhirams-1 commented on plugins/modules/zhmc_user.py
> +                        user_name, update_props)
Done

2024-06-16 11:11 UTC, andy-maier approved these changes

2024-06-16 11:15 UTC, andy-maier commented
Rebased to pick up fix for Ansible 10 that caused the previous failure.
Also squashed the commits into a single one to keep the commit history clean.

2024-06-16 11:21 UTC, merged